# TODO: ensure Required vars are defined.
lustre_reformat: false # Optional. Set true to reformat all mgt/mdt/ost, e.g. if needed to change configuration. WARNING WILL DELETE DATA. Default false. # TODO: guard this somehow?
lustre_fs_name: "{{ mandatory }}" # Required. Name of filesystem
lustre_mgs_addr: "{{ mandatory }}" # Required. IP of MGS.
# lustre_mgs_lnet: '' # TODO: Currently just use lustre_lnet but this might be different with multiple networks.
lustre_mgt: '' # Optional. Path of block device to use for mgt. Default '' does not create mgt (and hence mgs).
lustre_mdts: {} # Optional. Mapping with key: int, lustre-filesystem-unique index for mdt;  value: path of block device to use for mdt. Default {} does not create mdt (and hence mds).
lustre_osts: {} # Optional. Mapping key: int, lustre-filesystem-unique index for ost;  value: path of block device to use for ost. Default {} does not create ost (and hence oss).
lustre_lnet: tcp # Optional. Name of lnet. Default 'tcp'
